import 'public/css/bootstrap.min.css'
import 'public/css/font-awesome.min.css'
// import 'public/css/owl .carousel.min.css'
import 'public/css/owl.theme.default.min.css'
import 'public/css/style.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ProviderLayout from "./provider-layout";

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Металлообработка',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <ProviderLayout>
            {children}
          </ProviderLayout>
          {/*<a href="/#" className="cd-top">Вверх</a>*/}
          {/*<Link href="#">Вверх</Link>*/}
        </body>
    </html>
  )
}
